---
# Tasks for loading testing data

  - name: Creating folder for uploading script
    file:
      path: /opt/metadata-uploader
      state: directory

  - name: Placing testing data file to machine
    copy:
      src: "{{ role_path }}/files/test.mac"
      dest: /opt/metadata-uploader  
  
  - name: Copying insert case in database
    copy:
      src: "{{ role_path }}/files/insert_test_case.sql"
      dest: /tmp
   